Attribute VB_Name = "PrintRegFormmod"
Option Explicit


Public Sub PrintRegForm()

' Display the print dialog
Dim y As Integer

    frmPAWndc.dlgDBOpen.CancelError = True
    On Error GoTo PrintCanceled

    frmPAWndc.dlgDBOpen.ShowPrinter

    On Error GoTo 0

    ' start to printing

    Screen.MousePointer = vbHourglass

    Printer.ScaleMode = 4 ' character mode
    Printer.Font.Size = 10
    Printer.CurrentX = 2
    Printer.Print " DATE: " & Format$(Now, "MM/DD/YY");

    Printer.CurrentX = 23
    Printer.Print "Pro Application Creator Registration Form";

    Printer.CurrentX = 75
    Printer.Print "Page # " & Printer.Page

    y = Printer.CurrentY + 1  ' Set position for line.
    ' Draw a line across page.
    Printer.Line (0, y)-(Printer.ScaleWidth, y) ' Draw line.

    Printer.Print
    Printer.Print "    Pro Application Creator is not free software and requires registration."
    Printer.Print "    There are two classes of registration which are dependant upon "
    Printer.Print "    use: Commercial."
    Printer.Print
    Printer.Print "    Registration of Pro Application Creator is free for Non-commercial uses."
    Printer.Print "    Personal use only, source code generated by use of product may be"
    Printer.Print "    modified and used in your personal application Source code available"
    Printer.Print "    as an option for an additional free"
    Printer.Print
    Printer.Print "    Registration of Pro Application Creator for commercial use is $169.95. "
    Printer.Print "    Commercial uses are: Inclusion of Pro Application Creator or Source "
    Printer.Print "    Code 'generated' into ANY product that is to be sold for profit, or"
    Printer.Print "    any use of this program in a business environment. Any program that is"
    Printer.Print "    sold as a product for profit, or use in a corporate environment fits"
    Printer.Print "    this category. Commercial registration includes the source code for"
    Printer.Print "    Pro Application Creator in Visual Basic 6.0(Microsoft)."
    y = Printer.CurrentY + 1  ' Set position for line.
    ' Draw a line across page.
    Printer.Line (0, y)-(Printer.ScaleWidth, y) ' Draw line.
    Printer.Print
    Printer.Print "                               REGISTRATION FORM "

    y = Printer.CurrentY + 1  ' Set position for line.
    ' Draw a line across page.
    Printer.Line (0, y)-(Printer.ScaleWidth, y) ' Draw line.
    Printer.Print
    Printer.Print "     Program                      Registration Amount            Enclosed"
    Printer.Print "                               Commercial / Non-commercial"
    Printer.Print "     Pro Application 6.0        $169.95   / free               _____________"
    Printer.Print
    Printer.Print "     If you want the Source, please check here, and sign below _____________"
    Printer.Print
    Printer.Print "     PAYMENT BY:"
    Printer.Print
    Printer.Print "     Check/Money Order enclosed for $_________________________"
    Printer.Print
    Printer.Print
    Printer.Print "     MAILING ADDRESS:"
    Printer.Print
    Printer.Print "     Name___________________________________________________________________"
    Printer.Print
    Printer.Print "     Company________________________________________________________________"
    Printer.Print
    Printer.Print "     Address________________________________________________________________"
    Printer.Print
    Printer.Print "            ________________________________________________________________"
    Printer.Print
    Printer.Print "     City/State/Province____________________________________________________"
    Printer.Print
    Printer.Print "     Country/Postal Code____________________________________________________"
    Printer.Print
    Printer.Print "     Pro Application Creator will be used for________________________________"
    Printer.Print
    Printer.Print "     _______________________________________________________________________"
    Printer.Print
    Printer.Print
    Printer.Print "     Signature___________________________________     Date__________________"
    Printer.Print
    Printer.Print "     SEND TO:  Raymond E Dixon"
    Printer.Print "      tvmancet@hotmail.com "

    ' near the bottom of the page so
    ' start a new page

    If Printer.CurrentY > 45 Then
        Printer.NewPage
    End If

    Printer.EndDoc

    MsgBox " Windows  is printing all records.", vbInformation

    Screen.MousePointer = vbDefault

Exit Sub

PrintCanceled:
    On Error GoTo 0

End Sub


