Attribute VB_Name = "WriteSearchFormdao"
Option Explicit


Public Sub WriteSearchForm()
Dim fh As Integer

    fh = FreeFile
    Open gsAppPath & "\frm" & "Search.FRM" For Output As #fh

    Print #fh, "VERSION 5.00"
    Print #fh, "Begin VB.Form frmSearch"
    Print #fh, "   BorderStyle     =   3  'Fixed Dialog"
    Print #fh, "   Caption         =   " & Chr$(34) & "Find Record" & Chr$(34)
    Print #fh, "   Height          =   2820"
    Print #fh, "   Left            =   2085"
    Print #fh, "   MaxButton       =   0   'False"
    Print #fh, "   MinButton       =   0   'False"
    Print #fh, "   ScaleHeight     =   2397.11"
    Print #fh, "   ScaleMode       =   0  'User"
    Print #fh, "   ScaleWidth      =   5114.736"
    Print #fh, "   Top             =   1890"
    Print #fh, "   Width           =   5205"
    Print #fh, "   Begin VB.OptionButton optFindType"
    Print #fh, "      Caption         =   " & Chr$(34) & "FindLast" & Chr$(34)
    Print #fh, "      Height          =   255"
    Print #fh, "      Index           =   3"
    Print #fh, "      Left            =   2760"
    Print #fh, "      TabIndex        =   11"
    Print #fh, "      Top             =   1440"
    Print #fh, "      Width           =   2055"
    Print #fh, "   End"
    Print #fh, "   Begin VB.OptionButton optFindType"
    Print #fh, "      Caption         =   " & Chr$(34) & "FindPrevious" & Chr$(34)
    Print #fh, "      Height          =   255"
    Print #fh, "      Index           =   2"
    Print #fh, "      Left            =   2760"
    Print #fh, "      TabIndex        =   10"
    Print #fh, "      Top             =   1200"
    Print #fh, "      Width           =   2055"
    Print #fh, "   End"
    Print #fh, "   Begin VB.OptionButton optFindType"
    Print #fh, "      Caption         =   " & Chr$(34) & "FindNext" & Chr$(34)
    Print #fh, "      Height          =   255"
    Print #fh, "      Index           =   1"
    Print #fh, "      Left            =   2760"
    Print #fh, "      TabIndex        =   9"
    Print #fh, "      Top             =   960"
    Print #fh, "      Width           =   2055"
    Print #fh, "   End"
    Print #fh, "   Begin VB.OptionButton optFindType"
    Print #fh, "      Caption         =   " & Chr$(34) & "FindFirst" & Chr$(34)
    Print #fh, "      Height          =   255"
    Print #fh, "      Index           =   0"
    Print #fh, "      Left            =   2760"
    Print #fh, "      TabIndex        =   8"
    Print #fh, "      Top             =   720"
    Print #fh, "      Value           =   -1  'True"
    Print #fh, "      Width           =   2055"
    Print #fh, "   End"
    Print #fh, "   Begin VB.ListBox lstFields"
    Print #fh, "      BackColor       =   &H00FFFFFF&"
    Print #fh, "      Height          =   1425"
    Print #fh, "      Left            =   240"
    Print #fh, "      TabIndex        =   2"
    Print #fh, "      Top             =   360"
    Print #fh, "      Width           =   1695"
    Print #fh, "   End"
    Print #fh, "   Begin VB.ListBox lstOperators"
    Print #fh, "      BackColor       =   &H00FFFFFF&"
    Print #fh, "      Height          =   1425"
    Print #fh, "      Left            =   2040"
    Print #fh, "      TabIndex        =   7"
    Print #fh, "      Top             =   360"
    Print #fh, "      Width           =   615"
    Print #fh, "   End"
    Print #fh, "   Begin VB.TextBox txtExpression"
    Print #fh, "      BackColor       =   &H00FFFFFF&"
    Print #fh, "      Height          =   285"
    Print #fh, "      Left            =   2760"
    Print #fh, "      TabIndex        =   1"
    Print #fh, "      Top             =   360"
    Print #fh, "      Width           =   2055"
    Print #fh, "   End"
    Print #fh, "   Begin VB.CommandButton cmdOK"
    Print #fh, "      Caption         =   " & Chr$(34) & "&OK" & Chr$(34)
    Print #fh, "      Default         =   -1  'True"
    Print #fh, "      Enabled         =   0   'False"
    Print #fh, "      Height          =   372"
    Print #fh, "      Left            =   600"
    Print #fh, "      TabIndex        =   4"
    Print #fh, "      Top             =   1919"
    Print #fh, "      Width           =   1691"
    Print #fh, "   End"
    Print #fh, "   Begin VB.CommandButton cmdCancel"
    Print #fh, "      Cancel          =   -1  'True"
    Print #fh, "      Caption         =   " & Chr$(34) & "&Cancel" & Chr$(34)
    Print #fh, "      Height          =   372"
    Print #fh, "      Left            =   2879"
    Print #fh, "      TabIndex        =   5"
    Print #fh, "      Top             =   1919"
    Print #fh, "      Width           =   1691"
    Print #fh, "   End"
    Print #fh, "   Begin VB.Label lblLabels"
    Print #fh, "      AutoSize        =   -1  'True"
    Print #fh, "      Caption         =   " & Chr$(34) & "Operators: " & Chr$(34)
    Print #fh, "      Height          =   195"
    Print #fh, "      Index           =   0"
    Print #fh, "      Left            =   1980"
    Print #fh, "      TabIndex        =   6"
    Print #fh, "      Top             =   120"
    Print #fh, "      Width           =   780"
    Print #fh, "   End"
    Print #fh, "   Begin VB.Label lblLabels"
    Print #fh, "      AutoSize        =   -1  'True"
    Print #fh, "      Caption         =   " & Chr$(34) & "Fields: " & Chr$(34)
    Print #fh, "      Height          =   195"
    Print #fh, "      Index           =   1"
    Print #fh, "      Left            =   240"
    Print #fh, "      TabIndex        =   3"
    Print #fh, "      Top             =   120"
    Print #fh, "      Width           =   495"
    Print #fh, "   End"
    Print #fh, "   Begin VB.Label lblLabels"
    Print #fh, "      AutoSize        =   -1  'True"
    Print #fh, "      Caption         =   " & Chr$(34) & "Value or Expression: " & Chr$(34)
    Print #fh, "      Height          =   195"
    Print #fh, "      Index           =   2"
    Print #fh, "      Left            =   3000"
    Print #fh, "      TabIndex        =   0"
    Print #fh, "      Top             =   120"
    Print #fh, "      Width           =   1485"
    Print #fh, "   End"
    Print #fh, "End"
    Print #fh, "Attribute VB_Name = " & Chr$(34) & "frmSearch" & Chr$(34)
    Print #fh, "Attribute VB_Creatable = False"
    Print #fh, "Attribute VB_Exposed = False"
    Print #fh, "Option Explicit"
    Print #fh, "Dim gbNotFound As Boolean"
    Print #fh, ""
    Print #fh, "Private Sub cmdCancel_Click()"
    Print #fh, "  Hide"
    Print #fh, "  'set the flag for the recordset"
    Print #fh, "  gbFindFailed = True"
    Print #fh, "End Sub"
    Print #fh, ""
    Print #fh, "Private Sub optFindType_Click(Index As Integer)"
    Print #fh, "  gnFindType = Index"
    Print #fh, "End Sub"
    Print #fh, ""
    Print #fh, "Private Sub txtExpression_Change()"
    Print #fh, "  If Len(lstFields.Text) > 0 And Len(lstOperators.Text) > 0 And" & " Len(txtExpression.Text) > 0 Then"
    Print #fh, "    cmdOK.Enabled = True"
    Print #fh, "  Else"
    Print #fh, "    cmdOK.Enabled = False"
    Print #fh, "  End If"
    Print #fh, "End Sub"
    Print #fh, ""
    Print #fh, "Private Sub lstFields_Click()"
    Print #fh, "  If Len(lstFields.Text) > 0 And Len(lstOperators.Text) > 0 And" & " Len(txtExpression.Text) > 0 Then"
    Print #fh, "    cmdOK.Enabled = True"
    Print #fh, "  Else"
    Print #fh, "    cmdOK.Enabled = False"
    Print #fh, "  End If"
    Print #fh, "End Sub"
    Print #fh, ""
    Print #fh, "Private Sub lstOperators_Click()"
    Print #fh, "  If Len(lstFields.Text) > 0 And Len(lstOperators.Text) > 0 And" & " Len(txtExpression.Text) > 0 Then"
    Print #fh, "    cmdOK.Enabled = True"
    Print #fh, "  Else"
    Print #fh, "    cmdOK.Enabled = False"
    Print #fh, "  End If"
    Print #fh, "End Sub"
    Print #fh, ""
    Print #fh, "Private Sub cmdOK_Click()"
    Print #fh, ""
    Print #fh, "   Dim i As Integer"
    Print #fh, ""
    Print #fh, "   i = lstFields.ListIndex"
    Print #fh, "   gbNotFound = False"
    Print #fh, "   Screen.MousePointer = vbHourglass"
    Print #fh, ""
    Print #fh, "   gsFindField = lstFields.Text"
    Print #fh, "   gsFindExpr = txtExpression.Text"
    Print #fh, "   gsFindOp = lstOperators.Text"
    Print #fh, ""
    Print #fh, "   Hide"
    Print #fh, "   Screen.MousePointer = vbDefault"
    Print #fh, "End Sub"
    Print #fh, "Private Sub Form_Load()"
    Print #fh, ""
    Print #fh, "    '  center form"
    Print #fh, "    CenterMe Me"
    Print #fh, ""
    Print #fh, "  lstOperators.AddItem ""="""
    Print #fh, "  lstOperators.AddItem ""<="""
    Print #fh, "  lstOperators.AddItem "">="""
    Print #fh, "  lstOperators.AddItem ""<>"""
    Print #fh, "  lstOperators.AddItem ""<"""
    Print #fh, "  lstOperators.AddItem "">"""
    Print #fh, "  lstOperators.AddItem ""Like """
    Print #fh, "  gbNotFound = False"
    Print #fh, "End Sub"

    Close #fh

End Sub


