Attribute VB_Name = "WriteWaitFormdao"
Option Explicit


Public Sub WriteWaitForm(fh As Integer)

    Print #fh, "VERSION 5.00"
    Print #fh, "Begin VB.Form FrmWait"
    Print #fh, "   Appearance      =   0  'Flat"
    Print #fh, "   BackColor       =   &H00C0C0C0&"
    Print #fh, "   ClientHeight    =   3015"
    Print #fh, "   ClientLeft      =   2355"
    Print #fh, "   ClientTop       =   1320"
    Print #fh, "   ClientWidth     =   6300"
    Print #fh, "   BeginProperty Font"
    Print #fh, "      name            =   " & Chr$(34) & "MS Sans Serif" & Chr$(34)
    Print #fh, "      charset         =   0"
    Print #fh, "      weight          =   700"
    Print #fh, "      size            =   8.25"
    Print #fh, "      underline       =   0   'False"
    Print #fh, "      italic          =   0   'False"
    Print #fh, "      strikethrough   =   0   'False"
    Print #fh, "   EndProperty"
    Print #fh, "   ForeColor       =   &H00000000&"
    Print #fh, "   Height          =   3420"
    Print #fh, "   Left            =   2295"
    Print #fh, "   LinkTopic       =   " & Chr$(34) & "Form1" & Chr$(34)
    Print #fh, "   MaxButton       =   0   'False"
    Print #fh, "   MinButton       =   0   'False"
    Print #fh, "   ScaleHeight     =   3015"
    Print #fh, "   ScaleWidth      =   6300"
    Print #fh, "   Top             =   975"
    Print #fh, "   Width           =   6420"
    Print #fh, "   Begin VB.PictureBox ProgressBar"
    Print #fh, "      Align           =   2  'Align Bottom"
    Print #fh, "      Height          =   390"
    Print #fh, "      Left            =   0"
    Print #fh, "      AutoReDraw      =   -1"
    Print #fh, "      TabIndex        =   0"
    Print #fh, "   End"
    Print #fh, "   Begin VB.Label status"
    Print #fh, "      BackColor       =   &H00FFFFFF&"
    Print #fh, "      BorderStyle     =   1  'Fixed Single"
    Print #fh, "      Height          =   975"
    Print #fh, "      Left            =   1380"
    Print #fh, "      TabIndex        =   1"
    Print #fh, "      Top             =   840"
    Print #fh, "      Width           =   3975"
    Print #fh, "   End"
    Print #fh, "   Begin VB.Label Label1"
    Print #fh, "      Appearance      =   0  'Flat"
    Print #fh, "      AutoSize        =   -1  'True"
    Print #fh, "      BackColor       =   &H00C0C0C0&"
    Print #fh, "      Caption         =   " & Chr$(34) & gsAppName & Chr$(34)
    Print #fh, "      BeginProperty Font"
    Print #fh, "         name            =   " & Chr$(34) & "MS Sans Serif" & Chr$(34)
    Print #fh, "         charset         =   0"
    Print #fh, "         weight          =   700"
    Print #fh, "         size            =   24"
    Print #fh, "         underline       =   0   'False"
    Print #fh, "         italic          =   0   'False"
    Print #fh, "         strikethrough   =   0   'False"
    Print #fh, "      EndProperty"
    Print #fh, "      ForeColor       =   &H00008000&"
    Print #fh, "      Height          =   555"
    Print #fh, "      Left            =   960"
    Print #fh, "      TabIndex        =   0"
    Print #fh, "      Top             =   180"
    Print #fh, "      Width           =   4725"
    Print #fh, "   End"
    Print #fh, "End"
    Print #fh, "Attribute VB_Name = " & Chr$(34) & "FrmWait" & Chr$(34)
    Print #fh, "Attribute VB_Creatable = False"
    Print #fh, "Attribute VB_Exposed = False"
    Print #fh, ""
    Print #fh, "Option Explicit"
    Print #fh, ""
    Print #fh, "Private Sub Form_Load()"
    Print #fh, "    On Error Resume Next"
    Print #fh, "    CenterMe me"
    Print #fh, "    Show"
    Print #fh, "End Sub"
    Print #fh, ""

End Sub


